server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:products.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
  sql:
    init:
      mode: always
      data-locations: classpath:data/products.sql